//const express = require('./config/express.js')
const mongodb = require('./config/mongoose.js')
// const stompclient =  require('./config/stompclient.js')
var db = mongodb()
//var app  = stompclient()